---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  web_replicas: 1
  task_replicas: 3
  admin_user: admin
  admin_password_secret: awx-admin-password
  ingress_type: ingress
  ingress_class_name: nginx
  ingress_hosts:
    - hostname: awx.home.kenitrahub.com
      tls_secret: awx-secret-tls
  ingress_annotations: |
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    environment: testing
  postgres_storage_class: longhorn
  postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 20Gi
  postgres_data_volume_init: true
  postgres_resource_requirements:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: '1'
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 100M
    limits:
      cpu: 2000m
      memory: 4Gi
      ephemeral-storage: 500M
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 4Gi
  ee_resource_requirements:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 1000m
      memory: 4Gi
