---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

secretGenerator:
  - name: awx-admin-password
    options:
      disableNameSuffixHash: true
    type: Opaque
    literals:
      - password=MySuperStrongPassw00rd!

resources:
  - awx.yaml
  - awx-mesh-ingress.yaml
