---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

secretGenerator:
  - name: redhat-operators-pull-secret
    options:
      disableNameSuffixHash: true
    literals:
      - operator=awx

resources:
  - github.com/ansible/awx-operator/config/default?ref=2.15.0

images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.15.0